import type { GameInfo } from '../../engine/gameData';
import { inferNeonEngineFromSlug } from './inferNeonFromSlug';
import type { NeonEngineKey } from './types';

/**
 * Per-game neon canvas engine. Optional `game.neonEngine` overrides this table.
 */
const ENGINE_BY_ID: Record<string, NeonEngineKey> = {
  astromath_wars: 'space',
  multiplication_meteors: 'space',
  fraction_frenzy: 'math',
  algebra_blaster: 'math',
  vocabulary_sniper: 'typing',
  grammar_gladiator: 'quiz',
  science_defender: 'quiz',
  history_timeline_rush: 'quiz',
  geometry_defender: 'geometry',
  sat_word_arena: 'typing',
  statistics_paintball: 'math',
  chem_lab_chaos: 'quiz',
  financial_literacy_run: 'math',
  coordinate_conquest: 'geometry',
  data_defender: 'quiz',
  wordwave_survival: 'space',
  skilldash: 'geometry',
  sentence_sprint: 'flappy',
  bull_run_logic: 'geometry',
  equation_escape: 'maze',
  maze_of_ratios: 'maze',
  physics_platform: 'geometry',
  word_rocket_run: 'flappy',
  logic_tunnel: 'geometry',
  history_dash: 'flappy',
  chem_jump: 'quiz',
  speed_reading_dash: 'typing',
  essay_builder_rush: 'typing',
  market_mayhem: 'math',
  debate_dash: 'quiz',
  geometry_glide: 'geometry',
  sentence_builder_pro: 'scramble',
  context_clue_hunt: 'memory',
  pattern_blast: 'memory',
  ratio_architect: 'math',
  timeline_builder: 'quiz',
  proof_builder: 'quiz',
  word_connect_storm: 'memory',
  probability_quest: 'math',
  code_breaker: 'scramble',
  logic_tower: 'maze',
  word_balloon_pop: 'typing',
  number_catch: 'breakout',
  grammar_clicker: 'typing',
  flash_fact_frenzy: 'quiz',
  speed_multiplication: 'math',
  spelling_sniper: 'typing',
  color_equation: 'math',
  quick_sat: 'quiz',
  brain_boost: 'quiz',
  memory_matrix: 'memory',
  geometry_runner_3d: 'geometry',
  math_galaxy_3d: 'asteroids',
  word_world_3d: 'maze',
  vr_math_dojo: 'placeholder',
  storm_defenders: 'td',
  storm_defenders_vr: 'geometry',

  // StormNeon — Replit signature slugs → shared neon factories
  'typing-storm': 'typing',
  'speed-typer': 'typing',
  'word-blitz': 'typing',
  'math-storm': 'math',
  'number-battle': 'math',
  'times-table-titan': 'math',
  'math-elite': 'math',
  'fraction-fighter': 'math',
  'geography-quest': 'quiz',
  'world-explorer': 'quiz',
  'science-quest': 'quiz',
  'history-blast': 'quiz',
  'vocab-blast': 'quiz',
  'brain-blitz': 'quiz',
  'code-quest': 'quiz',
  'memory-matrix': 'memory',
  'pattern-storm': 'memory',
  'word-scramble-x': 'scramble',
  'anagram-storm': 'scramble',
  'spelling-quest': 'scramble',
  'snake-neon': 'snake',
  'python-pro': 'snake',
  'neon-viper': 'snake',
  'neon-viper-xl': 'snake',
  'neon-breakout': 'breakout',
  'brick-crusher': 'breakout',
  'arkanoid-x': 'breakout',
  'space-raiders': 'space',
  'galaxy-storm': 'space',
  'alien-blitz': 'space',
  'tetris-neon': 'tetris',
  'block-storm': 'tetris',
  'stack-attack': 'tetris',
  'grid-master': 'tetris',
  'neon-jump': 'geometry',
  'platform-storm': 'geometry',
  'sky-runner': 'geometry',
  'asteroid-storm': 'asteroids',
  'space-rock': 'asteroids',
  'cosmic-blast': 'asteroids',
};

const CATEGORY_FALLBACK: Record<GameInfo['category'], NeonEngineKey> = {
  StormBattle: 'space',
  StormDash: 'geometry',
  StormPuzzle: 'memory',
  StormQuick: 'quiz',
  Storm3D: 'geometry',
  StormVR: 'geometry',
  StormNeon: 'typing',
  StormMario: 'geometry',
  StormRetro: 'space',
  StormEduPlus: 'quiz',
  StormElite: 'geometry',
};

export function resolveNeonEngine(game: GameInfo): NeonEngineKey {
  if (game.neonEngine) return game.neonEngine as NeonEngineKey;
  const mapped = ENGINE_BY_ID[game.id];
  if (mapped) return mapped;
  return inferNeonEngineFromSlug(game.id) ?? CATEGORY_FALLBACK[game.category] ?? 'geometry';
}
